#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="$HOME/pape"
BIN_DIR="$HOME/.local/bin"
VENV_DIR="$PROJECT_DIR/.venv"

echo "==> 项目目录: $PROJECT_DIR"
echo "==> 数据目录: $DATA_DIR"
echo "==> 启动器  : $BIN_DIR/pape"

if ! command -v python3 >/dev/null 2>&1; then
  echo "错误: 未找到 python3" >&2
  exit 1
fi

PY_VER="$(python3 -c 'import sys;print("%d.%d"%sys.version_info[:2])')"
echo "==> Python 版本: $PY_VER"

if [ ! -d "$VENV_DIR" ]; then
  echo "==> 创建 venv: $VENV_DIR"
  python3 -m venv "$VENV_DIR"
else
  echo "==> 复用已有 venv: $VENV_DIR"
fi

echo "==> 升级 pip / 安装依赖"
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet -r "$PROJECT_DIR/requirements.txt"

echo "==> 把 pape 包以 editable 模式装进 venv（让命令在任意目录可用）"
"$VENV_DIR/bin/pip" install --quiet -e "$PROJECT_DIR" --no-deps

mkdir -p "$DATA_DIR/pdf" "$BIN_DIR"

LAUNCHER="$BIN_DIR/pape"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by pape install.sh — do not edit directly.
# Note: we call the venv's entry-point script (not 'python -m pape') so that
# CWD isn't added to sys.path. Otherwise a namespace-package collision with
# the user's ~/pape/ data dir would shadow our package.
exec "$VENV_DIR/bin/pape" "\$@"
EOF
chmod +x "$LAUNCHER"
echo "==> 启动器已写入: $LAUNCHER"

case ":$PATH:" in
  *":$HOME/.local/bin:"*)
    echo "✔ ~/.local/bin 已在 PATH，可直接运行：pape --help"
    ;;
  *)
    echo
    echo "⚠ ~/.local/bin 不在你的 PATH 中。请把下面这行加到 ~/.zshrc，然后重开终端："
    echo '    export PATH="$HOME/.local/bin:$PATH"'
    echo
    echo "或者直接通过绝对路径调用： $LAUNCHER --help"
    ;;
esac
